/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'
import { Route as ListsNewRouteImport } from './routes/lists/new'
import { Route as ListsIdRouteImport } from './routes/lists/$id'
import { Route as AuthSignoutRouteImport } from './routes/auth/signout'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ShareShareIdOpengraphImageRouteImport } from './routes/share/$shareId.opengraph-image'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsNewRoute = ListsNewRouteImport.update({
  id: '/lists/new',
  path: '/lists/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/auth/signout',
  path: '/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdOpengraphImageRoute =
  ShareShareIdOpengraphImageRouteImport.update({
    id: '/opengraph-image',
    path: '/opengraph-image',
    getParentRoute: () => ShareShareIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/lists/$id': typeof ListsIdRoute
  '/lists/new': typeof ListsNewRoute
  '/share/$shareId': typeof ShareShareIdRouteWithChildren
  '/share/$shareId/opengraph-image': typeof ShareShareIdOpengraphImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/lists/$id': typeof ListsIdRoute
  '/lists/new': typeof ListsNewRoute
  '/share/$shareId': typeof ShareShareIdRouteWithChildren
  '/share/$shareId/opengraph-image': typeof ShareShareIdOpengraphImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/lists/$id': typeof ListsIdRoute
  '/lists/new': typeof ListsNewRoute
  '/share/$shareId': typeof ShareShareIdRouteWithChildren
  '/share/$shareId/opengraph-image': typeof ShareShareIdOpengraphImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/auth/callback'
    | '/auth/signout'
    | '/lists/$id'
    | '/lists/new'
    | '/share/$shareId'
    | '/share/$shareId/opengraph-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/auth/callback'
    | '/auth/signout'
    | '/lists/$id'
    | '/lists/new'
    | '/share/$shareId'
    | '/share/$shareId/opengraph-image'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/auth/callback'
    | '/auth/signout'
    | '/lists/$id'
    | '/lists/new'
    | '/share/$shareId'
    | '/share/$shareId/opengraph-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignoutRoute: typeof AuthSignoutRoute
  ListsIdRoute: typeof ListsIdRoute
  ListsNewRoute: typeof ListsNewRoute
  ShareShareIdRoute: typeof ShareShareIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/new': {
      id: '/lists/new'
      path: '/lists/new'
      fullPath: '/lists/new'
      preLoaderRoute: typeof ListsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signout': {
      id: '/auth/signout'
      path: '/auth/signout'
      fullPath: '/auth/signout'
      preLoaderRoute: typeof AuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId/opengraph-image': {
      id: '/share/$shareId/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/share/$shareId/opengraph-image'
      preLoaderRoute: typeof ShareShareIdOpengraphImageRouteImport
      parentRoute: typeof ShareShareIdRoute
    }
  }
}

interface ShareShareIdRouteChildren {
  ShareShareIdOpengraphImageRoute: typeof ShareShareIdOpengraphImageRoute
}

const ShareShareIdRouteChildren: ShareShareIdRouteChildren = {
  ShareShareIdOpengraphImageRoute: ShareShareIdOpengraphImageRoute,
}

const ShareShareIdRouteWithChildren = ShareShareIdRoute._addFileChildren(
  ShareShareIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  ListsIdRoute: ListsIdRoute,
  ListsNewRoute: ListsNewRoute,
  ShareShareIdRoute: ShareShareIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
